// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb9n9VsdYExFh8nDekx6AquJPZxqPjeB4',
    appId: '1:380487807369:web:407d2b671b1d469561f158',
    messagingSenderId: '380487807369',
    projectId: 'bilgiislemkapi',
    authDomain: 'bilgiislemkapi.firebaseapp.com',
    storageBucket: 'bilgiislemkapi.appspot.com',
    measurementId: 'G-TLVXZCH0ZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjJ2G2X92y_urkIh-bmf3nu5UPLOMDToA',
    appId: '1:380487807369:android:6364f651582d974a61f158',
    messagingSenderId: '380487807369',
    projectId: 'bilgiislemkapi',
    storageBucket: 'bilgiislemkapi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Ew1Xvsl90dTWXtBGYe1tOHB2znUcPHI',
    appId: '1:380487807369:ios:75b6d9b2d7b46ef161f158',
    messagingSenderId: '380487807369',
    projectId: 'bilgiislemkapi',
    storageBucket: 'bilgiislemkapi.appspot.com',
    iosBundleId: 'com.example.bikapikontrolsistemi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Ew1Xvsl90dTWXtBGYe1tOHB2znUcPHI',
    appId: '1:380487807369:ios:f4ce25643d00cecb61f158',
    messagingSenderId: '380487807369',
    projectId: 'bilgiislemkapi',
    storageBucket: 'bilgiislemkapi.appspot.com',
    iosBundleId: 'com.example.bikapikontrolsistemi.RunnerTests',
  );
}
